#!/bin/sh
# Script to make python-gammu release

VERSION=`sed -n "s/VERSION = '\(.*\)'/\\1/p" setup.py`

# Create tag 
git tag -s "$VERSION" -m "Version $VERSION"

# Create tarballs
./setup.py sdist --formats=bztar,gztar,zip

# Upload to pypi
twine upload dist/python-gammu-$version.*

# Upload to primary mirror
scp dist/python-gammu-$VERSION.tar.bz2 dist/python-gammu-$VERSION.tar.gz dist/python-gammu-$VERSION.zip web:/srv/http/dl.cihar.com/python-gammu
